### ISSUE TITLE
beamerthemeseville.sty:154: ! LaTeX Error: File `beamerinnerthemetcolorbox.sty' not found

### ISSUE THREAD

**Issue by DanielRuf** [FMuro/seville#1]
It seems some file may be missing, tried to compile with tectonic.

**Comment by DanielRuf** [comment]
I've used now https://github.com/samcarter/beamertheme-tcolorbox/blob/main/beamerinnerthemetcolorbox.sty since the 2023 version of the packages is still work in progress: https://github.com/tectonic-typesetting/tectonic/issues/1086#issuecomment-1957661624

**Comment by DanielRuf** [comment]
In general it seems the wrong fonts are used, maybe it is due to the missing package for tectonic.

**Comment by FMuro** [comment]
@DanielRuf thanks for reporting!

Indeed, the best solution right now is:

- Grab and copy `beamerinnerthemetcolorbox.sty` in you project's folder.
- Use option `xelatex` if Adobe Source fonts are installed in your system, or the option `noto` otherwise.

This works for me in latest macOS, does it also work for you? 

Tomorrow, I'll update README.md to document this for `tectonic` users.

Hopefully, `tectonic` will play better with `tcolorbox` and Adobe's fonts in future versions.

**Comment by DanielRuf** [comment]
Thanks for the helpful instructions. I'm making some progress.
But not sure, why Source Sans 3 Bold is not found, it's installed as ttf.
The files are from https://fonts.google.com/specimen/Source+Sans+3

![grafik](https://github.com/FMuro/seville/assets/827205/eb083ad5-66ac-4d8e-9ca2-6901baa4b943)

![grafik](https://github.com/FMuro/seville/assets/827205/4fc0cf93-d4eb-4b9f-993f-043ec0a81342)

**Comment by DanielRuf** [comment]
I've switched now to fira but then I end up with another error:

![grafik](https://github.com/FMuro/seville/assets/827205/c1a65d6d-11d8-4f51-8d38-89417a7a372a)

I will try to find a solution, maybe I just have to wait for the new tectonic release for 2023.

**Comment by FMuro** [comment]
@DanielRuf I think I've fixed the Fira error, could you download the latest version and try? I've added the results of my tectonic tests at the bottom of the [options](https://github.com/FMuro/seville?tab=readme-ov-file#options) section of the README. I would also be very grateful if you could also check that the other possible options work for you. It looks like you're using Ubuntu, so I can't use the computer I'm writing from for testing, I'll try when I'm back home.

**Comment by DanielRuf** [comment]
@FMuro thanks, that seems to resolve the described error.

Currently it results in a segmentation fault. Not sure if it is because of ttf instead of otf. I will test this.

![grafik](https://github.com/FMuro/seville/assets/827205/95686e80-7c3f-4528-a001-258ebf4ae17b)

**Comment by DanielRuf** [comment]
Yes, replacing the ttf files with oft versions resolved the last problem:

![grafik](https://github.com/FMuro/seville/assets/827205/960e044e-6865-42f0-87c2-2d423cd7b14e)

![grafik](https://github.com/FMuro/seville/assets/827205/8d01df60-9213-4b05-9ea9-6f50f74e2b3d)

**Comment by DanielRuf** [comment]
> I would also be very grateful if you could also check that the other possible options work for you.

Can you list the combinations that I should try with `[...]`? Then I can create the MWEs and run tectonic over them.

> It looks like you're using Ubuntu

Right, Ubuntu 22.04.4 LTS.

**Comment by FMuro** [comment]
> Can you list the combinations that I should try with `[...]`? Then I can create the MWEs and run tectonic over them.

Sure!

- [ ] `\usetheme[xelatex]{seville}`

- [ ] `\usetheme[noto]{seville}`

- [ ] `\usetheme[fira]{seville}`

- [ ] `\usetheme[lmodern]{seville}`

**Comment by DanielRuf** [comment]
* [x] `\usetheme[xelatex]{seville}`

![grafik](https://github.com/FMuro/seville/assets/827205/4923e811-2e4a-41cf-9dc7-8a113d3426cd)

I have used the ttf fonts from https://fonts.google.com/?query=source - knowing that otf may work better, I have then used the otf version from these repos:
* https://github.com/adobe-fonts/source-sans
* https://github.com/adobe-fonts/source-code-pro
* https://github.com/adobe-fonts/source-serif

With these otf versions, it worked:

![grafik](https://github.com/FMuro/seville/assets/827205/a29292ba-31f8-4e46-8084-b9e60b274fc1)

[test3_xelatex.pdf](https://github.com/FMuro/seville/files/14608346/test3_xelatex.pdf)

* [x] `\usetheme[noto]{seville}`

![grafik](https://github.com/FMuro/seville/assets/827205/34228d0d-779f-43ca-bc2d-85b53c1c38e3)

[test3_noto.pdf](https://github.com/FMuro/seville/files/14608345/test3_noto.pdf)

* [x] `\usetheme[fira]{seville}`

![grafik](https://github.com/FMuro/seville/assets/827205/1b99b2d0-48b8-4527-8b79-378427b55b03)

[test3_fira.pdf](https://github.com/FMuro/seville/files/14608344/test3_fira.pdf)

* [x] `\usetheme[lmodern]{seville}`

![grafik](https://github.com/FMuro/seville/assets/827205/9aa33e22-9a56-43ec-bb46-0dc0f1e5177d)

[test3_lmodern.pdf](https://github.com/FMuro/seville/files/14608341/test3_lmodern.pdf)

**Comment by FMuro** [comment]
@DanielRuf wow, thanks a lot for taking the time to do this! I'm happy the theme now reasonably works with tectonic.
